apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM= # base64 encoded string for "postgres"
  postgres-password: cG9zdGdyZXM= # base64 encoded string for "admin@123"